var INTERACTIONS = [
  // ===== SEROTONERGA SYNDROM =====
  { a: ["N06AB"], b: ["N06AF"], s: "danger", t: "Serotonergt syndrom \u2014 kontraindicerat", d: "SSRI + MAO-h\u00e4mmare kan orsaka livshotande serotonergt syndrom (agitation, hypertermi, takykardi, neuromuskul\u00e4r hyperaktivitet).", r: "Minst 14 dagars uttv\u00e4ttningstid mellan SSRI och MAO-h\u00e4mmare. \u00d6verv\u00e4g alternativ behandling." },
  { a: ["N06AX"], b: ["N06AF"], s: "danger", t: "Serotonergt syndrom \u2014 kontraindicerat", d: "SNRI + MAO-h\u00e4mmare kan orsaka livshotande serotonergt syndrom.", r: "Minst 14 dagars uttv\u00e4ttningstid mellan SNRI och MAO-h\u00e4mmare." },
  { a: ["N06AB"], b: ["N02AX02"], s: "danger", t: "Serotonergt syndrom \u2014 f\u00f6rh\u00f6jd risk", d: "SSRI + tramadol \u00f6kar risken f\u00f6r serotonergt syndrom. Tramadol har serotonin\u00e5terupptagsh\u00e4mmande egenskaper.", r: "\u00d6verv\u00e4g paracetamol eller NSAID som alternativ sm\u00e4rtlindring. Vid behov av opioid: \u00f6verv\u00e4g morfin som har l\u00e4gre serotonerg effekt." },
  { a: ["N06AB"], b: ["N07BC02"], s: "danger", t: "Serotonergt syndrom \u2014 f\u00f6rh\u00f6jd risk", d: "SSRI + metadon \u00f6kar risken f\u00f6r serotonergt syndrom samt f\u00f6rl\u00e4ngd QT-tid.", r: "Monitorera EKG. \u00d6verv\u00e4g alternativ sm\u00e4rtlindring." },
  { a: ["N06AB"], b: ["N02CC"], s: "warn", t: "Serotonergt syndrom \u2014 potentiell risk", d: "SSRI + triptaner (migr\u00e4nmedicin) har i s\u00e4llsynta fall rapporterats orsaka serotonergt syndrom.", r: "Informera patienten om symtom. Risken \u00e4r l\u00e5g men klinisk vaksamhet rekommenderas." },
  { a: ["N06AB"], b: ["J01XX08"], s: "danger", t: "Serotonergt syndrom \u2014 kontraindicerat", d: "SSRI + linezolid (antibiotikum med MAO-h\u00e4mmande effekt) kan orsaka allvarligt serotonergt syndrom.", r: "Undvik kombinationen. \u00d6verv\u00e4g alternativt antibiotikum." },
  { a: ["N06AX12"], b: ["N02AX02"], s: "danger", t: "S\u00e4nkta kramptr\u00f6skeln \u2014 risk f\u00f6r kramper", d: "Bupropion s\u00e4nker kramptr\u00f6skeln och tramadol \u00f6kar kramprisken ytterligare.", r: "Undvik kombinationen. \u00d6verv\u00e4g alternativt antidepressivum eller sm\u00e4rtlindring." },

  // ===== BL\u00d6DNINGSRISK =====
  { a: ["B01AA03"], b: ["M01A"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "NSAID \u00f6kar bl\u00f6dningsrisken vid warfarinbehandling genom trombocyth\u00e4mning och p\u00e5verkan p\u00e5 magslemhinnan.", r: "\u00d6verv\u00e4g paracetamol som sm\u00e4rtlindring. Vid n\u00f6dv\u00e4ndig NSAID-behandling: monitorera PK/INR noggrant och \u00f6verv\u00e4g gastroskydd." },
  { a: ["B01AA03"], b: ["N02BA01"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "Acetylsalicylsyra i analgetisk dos \u00f6kar bl\u00f6dningsrisken vid warfarinbehandling.", r: "Undvik h\u00f6ga doser ASA. L\u00e5gdos-ASA (75\u2013160 mg) kan vid etablerad kardiovaskul\u00e4r sjukdom ges under noggrann PK/INR-monitorering." },
  { a: ["B01AA03"], b: ["B01AC04"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "Kombination av warfarin och trombocyth\u00e4mmande ASA \u00f6kar bl\u00f6dningsrisken signifikant.", r: "Gr\u00e4nsnytta vid etablerad kardiovaskul\u00e4r sjukdom. \u00d6verv\u00e4g indikationen och monitorera PK/INR." },
  { a: ["B01AF01"], b: ["M01A"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "NSAID + rivaroxaban \u00f6kar bl\u00f6dningsrisken genom synergistisk trombocyth\u00e4mning och GI-slemhinnep\u00e5verkan.", r: "\u00d6verv\u00e4g paracetamol. Vid n\u00f6dv\u00e4ndig NSAID-behandling: \u00f6verv\u00e4g gastroskydd och noggrann monitorering." },
  { a: ["B01AF02"], b: ["M01A"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "NSAID + apixaban \u00f6kar bl\u00f6dningsrisken genom synergistisk trombocyth\u00e4mning och GI-slemhinnep\u00e5verkan.", r: "\u00d6verv\u00e4g paracetamol. Vid n\u00f6dv\u00e4ndig NSAID-behandling: \u00f6verv\u00e4g gastroskydd och noggrann monitorering." },
  { a: ["B01AA03"], b: ["N06AB"], s: "warn", t: "\u00d6kad bl\u00f6dningsrisk", d: "SSRI \u00f6kar risken f\u00f6r GI-bl\u00f6dning vid warfarinbehandling genom p\u00e5verkan p\u00e5 trombocytaggregationen.", r: "Monitorera PK/INR. \u00d6verv\u00e4g mirtazapin som alternativt antidepressivum." },
  { a: ["B01AC04"], b: ["M01A"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "Klopidogrel + NSAID \u00f6kar bl\u00f6dningsrisken signifikant genom synergistisk trombocyth\u00e4mning.", r: "\u00d6verv\u00e4g paracetamol. Vid n\u00f6dv\u00e4ndig NSAID-behandling: h\u00e5ll kort behandlingstid och \u00f6verv\u00e4g gastroskydd." },
  { a: ["M01A"], b: ["N06AB"], s: "warn", t: "\u00d6kad bl\u00f6dningsrisk", d: "SSRI + NSAID \u00f6kar risken f\u00f6r \u00f6vre gastrointestinal bl\u00f6dning. SSRI p\u00e5verkar trombocytaggregationen och NSAID irriterar magslemhinnan additivt.", r: "\u00d6verv\u00e4g paracetamol som sm\u00e4rtlindring. Vid n\u00f6dv\u00e4ndig NSAID-behandling: \u00f6verv\u00e4g gastroskydd (PPI) och informera patienten om bl\u00f6dningssymtom." },
  { a: ["B01AA03"], b: ["J01XD01"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "Metronidazol h\u00e4mmar warfarins metabolism (CYP2C9) och kan kraftigt \u00f6ka PK/INR med bl\u00f6dningsrisk.", r: "Monitorera PK/INR inom 2\u20133 dagar efter ins\u00e4ttning. F\u00f6rv\u00e4nta dig dosreduktion av warfarin med 20\u201330 %. \u00d6verv\u00e4g alternativt antibiotikum." },
  { a: ["B01AA03"], b: ["J02AC01"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "Flukonazol h\u00e4mmar warfarins metabolism (CYP2C9) och kan orsaka kraftig INR-stegring med bl\u00f6dningsrisk.", r: "Monitorera PK/INR inom 2\u20133 dagar efter ins\u00e4ttning. F\u00f6rv\u00e4nta dig dosreduktion av warfarin. \u00d6verv\u00e4g alternativt antimykotikum." },
  { a: ["B01AA03"], b: ["J01MA02"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "Ciprofloxacin h\u00e4mmar warfarins metabolism och kan orsaka INR-stegring med bl\u00f6dningsrisk.", r: "Monitorera PK/INR inom 2\u20133 dagar efter ins\u00e4ttning. \u00d6verv\u00e4g alternativt antibiotikum." },

  // ===== HYPERKALEMI =====
  { a: ["C09A"], b: ["C03DA"], s: "danger", t: "Hyperkalemirisk", d: "ACE-h\u00e4mmare + kaliumsparande diuretika (spironolakton, eplerenon) kan orsaka allvarlig hyperkalemi.", r: "Kontrollera S-kalium regelbundet. \u00d6verv\u00e4g loopdiuretikum som alternativ." },
  { a: ["C09A"], b: ["C09C"], s: "warn", t: "Dubbel RAAS-blockad \u2014 risk f\u00f6r hypotension och hyperkalemi", d: "Kombination av ACE-h\u00e4mmare och ARB \u00f6kar risken f\u00f6r njurp\u00e5verkan och hyperkalemi utan dokumenterad mortalitetsvinst.", r: "Dubbel RAAS-blockad rekommenderas ej rutinm\u00e4ssigt. \u00d6verv\u00e4g alternativ kombination." },
  { a: ["C09A"], b: ["A12BA"], s: "danger", t: "Hyperkalemirisk", d: "ACE-h\u00e4mmare + kaliumtillskott kan orsaka allvarlig hyperkalemi.", r: "Kontrollera S-kalium f\u00f6re och under behandling. Undvik rutinm\u00e4ssiga kaliumtillskott." },
  { a: ["C09C"], b: ["C03DA"], s: "danger", t: "Hyperkalemirisk", d: "ARB + kaliumsparande diuretika (spironolakton, eplerenon) kan orsaka allvarlig hyperkalemi.", r: "Kontrollera S-kalium regelbundet. \u00d6verv\u00e4g loopdiuretikum som alternativ." },
  { a: ["C09A"], b: ["J01EA01"], s: "warn", t: "Hyperkalemirisk", d: "ACE-h\u00e4mmare + trimetoprim kan orsaka hyperkalemi genom additiv effekt p\u00e5 njurarnas kaliumuts\u00f6ndring.", r: "Kontrollera S-kalium vid l\u00e4ngre tids behandling. \u00d6verv\u00e4g alternativt antibiotikum." },

  // ===== BRADYKARDI / AV-BLOCK =====
  { a: ["C07A"], b: ["C08DA01"], s: "danger", t: "Risk f\u00f6r bradykardi och AV-block", d: "Betablockerare + verapamil kan orsaka uttalad bradykardi, AV-block och hypotension.", r: "Undvik kombinationen. \u00d6verv\u00e4g dihydropyridin-kalciumantagonist (amlodipin, felodipin) ist\u00e4llet." },
  // OBS: Diltiazem (C08DB01) finns ej i svenska FASS per 2026 — regeln \u00e4r kliniskt korrekt
  // men v\u00e4ntar p\u00e5 databas-t\u00e4ckning.
  { a: ["C07A"], b: ["C08DB01"], s: "danger", t: "Risk f\u00f6r bradykardi och AV-block", d: "Betablockerare + diltiazem kan orsaka bradykardi, AV-block och hypotension.", r: "Undvik kombinationen. \u00d6verv\u00e4g dihydropyridin-kalciumantagonist (amlodipin, felodipin) ist\u00e4llet." },
  { a: ["C01AA05"], b: ["C01BD01"], s: "danger", t: "\u00d6kad digoxintoxicitet", d: "Amiodaron \u00f6kar digoxinkoncentrationen kraftigt (50\u201370 %) med risk f\u00f6r allvarlig intoxikation.", r: "Halvera digoxindosen och monitorera S-digoxin och EKG. \u00d6verv\u00e4g alternativt antiarytmikum." },
  { a: ["C01AA05"], b: ["C08DA01"], s: "danger", t: "\u00d6kad digoxintoxicitet", d: "Verapamil \u00f6kar digoxinkoncentrationen med risk f\u00f6r intoxikation.", r: "Monitorera S-digoxin och EKG. \u00d6verv\u00e4g dosjustering eller alternativ behandling." },
  { a: ["B01AE07"], b: ["C08DA01"], s: "warn", t: "\u00d6kad dabigatrankoncentration \u2014 bl\u00f6dningsrisk", d: "Verapamil \u00f6kar dabigatrankoncentrationen med \u00f6kad bl\u00f6dningsrisk.", r: "\u00d6verv\u00e4g dosjustering. Undvik samtidig administrering om m\u00f6jligt." },

  // ===== SMAL TERAPEUTISK BREDD =====
  { a: ["N05AN01"], b: ["M01A"], s: "danger", t: "\u00d6kad litiumkoncentration \u2014 intoxikationsrisk", d: "NSAID kan \u00f6ka litiumkoncentrationen med 25\u201350 % och orsaka litiumintoxikation.", r: "Undvik kombinationen. \u00d6verv\u00e4g paracetamol. Vid n\u00f6dv\u00e4ndig NSAID-behandling: monitorera S-litium noggrant och justera dosen." },
  { a: ["N05AN01"], b: ["C03A"], s: "danger", t: "\u00d6kad litiumkoncentration \u2014 intoxikationsrisk", d: "Tiaziddiuretika minskar njurclearance av litium och kan orsaka intoxikation.", r: "Monitorera S-litium. \u00d6verv\u00e4g loopdiuretikum eller alternativ behandling." },
  { a: ["N05AN01"], b: ["C09A"], s: "warn", t: "\u00d6kad litiumkoncentration", d: "ACE-h\u00e4mmare kan \u00f6ka litiumkoncentrationen och orsaka intoxikation.", r: "Monitorera S-litium noggrant. \u00d6verv\u00e4g alternativt antihypertensivum." },
  { a: ["L04AX03"], b: ["M01A"], s: "danger", t: "\u00d6kad metotrexattoxicitet", d: "NSAID minskar njurclearance av metotrexat vilket kan orsaka allvarlig intoxikation (benm\u00e4rgssuppression, njursvikt).", r: "Undvik kombinationen. \u00d6verv\u00e4g paracetamol som sm\u00e4rtlindring." },
  { a: ["L04AX03"], b: ["J01EA01"], s: "danger", t: "\u00d6kad metotrexattoxicitet", d: "Trimetoprim minskar njurclearance av metotrexat och \u00f6kar risken f\u00f6r intoxikation.", r: "Undvik kombinationen. \u00d6verv\u00e4g alternativt antibiotikum." },
  { a: ["M04AA01"], b: ["L04AX01"], s: "danger", t: "\u00d6kad azatioprintoxicitet \u2014 benm\u00e4rgssuppression", d: "Allopurinol h\u00e4mmar metabolismen av azatioprin vilket kan orsaka allvarlig benm\u00e4rgssuppression.", r: "Minska azatioprindosen till 25 % av ursprungsdosen. Monitorera blodstatus." },
  { a: ["L04AX03"], b: ["J01C"], s: "danger", t: "\u00d6kad metotrexattoxicitet", d: "Penicilliner minskar njurclearance av metotrexat och kan orsaka allvarlig intoxikation med benm\u00e4rgssuppression.", r: "Monitorera njurfunktion och blodstatus. \u00d6verv\u00e4g alternativt antibiotikum (t.ex. erytromycin, klindamycin)." },
  { a: ["N03AX09"], b: ["N03AG01"], s: "danger", t: "\u00d6kad lamotriginniv\u00e5 \u2014 risk f\u00f6r allvarliga hudreaktioner", d: "Valproat \u00f6kar lamotriginkoncentrationen cirka 2\u00d7 via h\u00e4mning av glukuronidering. Risk f\u00f6r Stevens\u2013Johnsons syndrom vid snabb titrering.", r: "Halvera lamotrigindosen vid ins\u00e4ttning av valproat. Titrera lamotrigin l\u00e5ngsamt. Monitorera hudutslag." },
  { a: ["L04AX03"], b: ["A02BC"], s: "warn", t: "\u00d6kad metotrexattoxicitet", d: "Protonpumpsh\u00e4mmare kan minska njurclearance av metotrexat och \u00f6ka risken f\u00f6r intoxikation.", r: "\u00d6verv\u00e4g tillf\u00e4lligt uppeh\u00e5ll med PPI under metotrexatbehandling eller monitorera MTX-niv\u00e5er." },

  // ===== CYP-INTERAKTIONER =====
  { a: ["C10AA01"], b: ["J01FA09"], s: "danger", t: "Rabdomyolysrisk \u2014 kraftigt \u00f6kad simvastatinkoncentration", d: "Klaritromycin h\u00e4mmar CYP3A4 och \u00f6kar simvastatinkoncentrationen markant med risk f\u00f6r rabdomyolys.", r: "G\u00f6r uppeh\u00e5ll med simvastatin under antibiotikakuren. \u00d6verv\u00e4g rosuvastatin eller pravastatin som alternativ." },
  { a: ["C10AA01"], b: ["J02AC02"], s: "danger", t: "Rabdomyolysrisk \u2014 kraftigt \u00f6kad simvastatinkoncentration", d: "Itrakonazol \u00e4r en stark CYP3A4-h\u00e4mmare och \u00f6kar simvastatinkoncentrationen markant.", r: "Undvik kombinationen. G\u00f6r uppeh\u00e5ll med simvastatin under antimykotisk behandling." },
  { a: ["C10AA05"], b: ["J01FA09"], s: "warn", t: "\u00d6kad statinkoncentration \u2014 risk f\u00f6r myopati", d: "Klaritromycin \u00f6kar atorvastatinkoncentrationen via CYP3A4-h\u00e4mning.", r: "\u00d6verv\u00e4g tillf\u00e4lligt uppeh\u00e5ll eller dosreduktion av atorvastatin under antibiotikakuren." },
  { a: ["B01AC04"], b: ["A02BC01"], s: "warn", t: "Minskad klopidogreleffekt", d: "Omeprazol/esomprazol h\u00e4mmar CYP2C19 och minskar aktiveringen av klopidogrel med risk f\u00f6r minskad antitrombotisk effekt.", r: "\u00d6verv\u00e4g pantoprazol som alternativ PPI (svagare CYP2C19-h\u00e4mning)." },
  { a: ["L02BA01"], b: ["N06AB05"], s: "danger", t: "Minskad tamoxifeneffekt \u2014 \u00f6kad recidivrisk", d: "Paroxetin \u00e4r en stark CYP2D6-h\u00e4mmare och minskar aktiveringen av tamoxifen till endoxifen med risk f\u00f6r \u00f6kad recidivrisk vid br\u00f6stcancer.", r: "Byt till citalopram, escitalopram eller venlafaxin som har svag CYP2D6-h\u00e4mning." },
  { a: ["L02BA01"], b: ["N06AB03"], s: "danger", t: "Minskad tamoxifeneffekt \u2014 \u00f6kad recidivrisk", d: "Fluoxetin \u00e4r en stark CYP2D6-h\u00e4mmare och minskar aktiveringen av tamoxifen med risk f\u00f6r \u00f6kad recidivrisk.", r: "Byt till citalopram, escitalopram eller venlafaxin som alternativ." },
  { a: ["N06AX21"], b: ["L02BA01"], s: "warn", t: "M\u00f6jligt minskad tamoxifeneffekt", d: "Duloxetin \u00e4r en m\u00e5ttlig CYP2D6-h\u00e4mmare och kan minska aktiveringen av tamoxifen.", r: "\u00d6verv\u00e4g citalopram eller escitalopram som alternativt antidepressivum." },
  { a: ["C10AA01"], b: ["C08CA01"], s: "warn", t: "\u00d6kad statinkoncentration \u2014 risk f\u00f6r myopati", d: "Amlodipin h\u00e4mmar CYP3A4 milt och \u00f6kar simvastatinkoncentrationen med cirka 50 %. Vid samtidig behandling b\u00f6r simvastatindosen inte \u00f6verstiga 20 mg/dag.", r: "Begr\u00e4nsa simvastatindosen till 20 mg/dag. \u00d6vervaka tecken p\u00e5 muskelp\u00e5verkan. Rosuvastatin eller pravastatin p\u00e5verkas inte." },
  { a: ["C10AA"], b: ["C10AB04"], s: "danger", t: "Rabdomyolysrisk \u2014 kraftigt \u00f6kad statinkoncentration", d: "Gemfibrozil h\u00e4mmar glukuronideringen av statiner och \u00f6kar statinkoncentrationen markant med risk f\u00f6r rabdomyolys.", r: "Undvik kombinationen. \u00d6verv\u00e4g fenofibrat som har l\u00e4gre interaktionsrisk. Om kombination kr\u00e4vs: monitorera CK och avbryt vid muskelsymtom." },

  // ===== CARDIOVASKUL\u00c4RT =====
  { a: ["G04BE"], b: ["C01DA"], s: "danger", t: "Livshotande hypotension \u2014 kontraindicerat", d: "PDE5-h\u00e4mmare (sildenafil, tadalafil) + nitrater orsakar kraftig vasodilatation och kan leda till livshotande hypotension.", r: "Kontraindicerat. Minst 24 timmars uppeh\u00e5ll mellan preparaten (48 tim f\u00f6r tadalafil)." },
  { a: ["C07A"], b: ["A10A"], s: "warn", t: "Maskerade hypoglykemisymtom", d: "Betablockerare kan maskera symtom p\u00e5 hypoglykemi (takykardi, tremor) hos diabetespatienter.", r: "Informera patienten. \u00d6verv\u00e4g kardioselektiv betablockerare vid behov." },
  { a: ["C09A"], b: ["N02BA01"], s: "warn", t: "Minskad antihypertensiv effekt och njurp\u00e5verkan", d: "NSAID (inkl. ASA i analgetisk dos) kan minska den blodtryckss\u00e4nkande effekten av ACE-h\u00e4mmare och f\u00f6rs\u00e4mra njurfunktionen.", r: "Kontrollera blodtryck och njurfunktion. \u00d6verv\u00e4g paracetamol vid behov av analgetika." },

  // ===== NSAID + RAAS-blockad / diuretika (triple whammy) =====
  { a: ["M01A"], b: ["C09A"], s: "warn", t: "Minskad antihypertensiv effekt och njurp\u00e5verkan", d: "NSAID kan minska den blodtryckss\u00e4nkande effekten av ACE-h\u00e4mmare och f\u00f6rs\u00e4mra njurfunktionen, s\u00e4rskilt hos \u00e4ldre och vid redan nedsatt njurfunktion.", r: "Kontrollera blodtryck och njurfunktion inom 1\u20132 veckor. \u00d6verv\u00e4g paracetamol som sm\u00e4rtlindring." },
  { a: ["M01A"], b: ["C09C"], s: "warn", t: "Minskad antihypertensiv effekt och njurp\u00e5verkan", d: "NSAID kan minska den blodtryckss\u00e4nkande effekten av ARB och f\u00f6rs\u00e4mra njurfunktionen, s\u00e4rskilt hos \u00e4ldre och vid redan nedsatt njurfunktion.", r: "Kontrollera blodtryck och njurfunktion inom 1\u20132 veckor. \u00d6verv\u00e4g paracetamol som sm\u00e4rtlindring." },
  { a: ["M01A"], b: ["C03A"], s: "warn", t: "Minskad diuretisk effekt och njurp\u00e5verkan", d: "NSAID kan minska den diuretiska effekten av tiazider och \u00f6ka risken f\u00f6r akut njursvikt, s\u00e4rskilt vid samtidig RAAS-blockad.", r: "Monitorera njurfunktion och blodtryck. \u00d6verv\u00e4g paracetamol som sm\u00e4rtlindring." },
  { a: ["M01A"], b: ["C03C"], s: "warn", t: "Minskad diuretisk effekt och njurp\u00e5verkan", d: "NSAID kan minska den diuretiska effekten av loopdiuretika och \u00f6ka risken f\u00f6r akut njursvikt, s\u00e4rskilt vid samtidig RAAS-blockad.", r: "Monitorera njurfunktion och v\u00e4tskestatus. \u00d6verv\u00e4g paracetamol som sm\u00e4rtlindring." },

  // ===== QT-F\u00d6RL\u00c4NGNING =====
  { a: ["N06AB04"], b: ["C01BD01"], s: "warn", t: "F\u00f6rl\u00e4ngd QT-tid \u2014 risk f\u00f6r ventrikul\u00e4r arytmi", d: "Citalopram + amiodaron kan f\u00f6rl\u00e4nga QT-tiden additivt med risk f\u00f6r torsades de pointes.", r: "Monitorera EKG. \u00d6verv\u00e4g sertralin som alternativt SSRI (mindre QT-p\u00e5verkan)." },
  { a: ["N06AB10"], b: ["C01BD01"], s: "warn", t: "F\u00f6rl\u00e4ngd QT-tid \u2014 risk f\u00f6r ventrikul\u00e4r arytmi", d: "Escitalopram + amiodaron kan f\u00f6rl\u00e4nga QT-tiden additivt.", r: "Monitorera EKG. \u00d6verv\u00e4g sertralin som alternativt SSRI." },
  { a: ["N07BC02"], b: ["N06AB04"], s: "warn", t: "F\u00f6rl\u00e4ngd QT-tid \u2014 risk f\u00f6r ventrikul\u00e4r arytmi", d: "Metadon + citalopram f\u00f6rl\u00e4nger QT-tiden additivt.", r: "Monitorera EKG f\u00f6re och under behandling. \u00d6verv\u00e4g alternativt antidepressivum." },
  { a: ["N07BC02"], b: ["J01M"], s: "warn", t: "F\u00f6rl\u00e4ngd QT-tid \u2014 risk f\u00f6r ventrikul\u00e4r arytmi", d: "Metadon + fluorokinoloner kan f\u00f6rl\u00e4nga QT-tiden additivt.", r: "Monitorera EKG. \u00d6verv\u00e4g alternativt antibiotikum." },
  { a: ["N07BC02"], b: ["C01BD01"], s: "danger", t: "F\u00f6rl\u00e4ngd QT-tid \u2014 risk f\u00f6r ventrikul\u00e4r arytmi", d: "B\u00e5de metadon och amiodaron f\u00f6rl\u00e4nger QT-tiden - kombinationen kan utl\u00f6sa allvarlig ventrikul\u00e4r arytmi.", r: "Monitorera EKG regelbundet. \u00d6verv\u00e4g alternativt antiarytmikum eller sm\u00e4rtlindring." },

  // ===== \u00d6VRIGA INTERAKTIONER =====
  // OBS: Tizanidin (M03BX02) finns ej i svenska FASS per 2026 — regeln \u00e4r kliniskt korrekt
  // men v\u00e4ntar p\u00e5 databas-t\u00e4ckning.
  { a: ["J01MA02"], b: ["M03BX02"], s: "danger", t: "Kraftig tizanidineffekt \u2014 hypotoni och sedering", d: "Ciprofloxacin h\u00e4mmar CYP1A2 och \u00f6kar tizanidinkoncentrationen kraftigt med risk f\u00f6r markant hypotoni och sedering.", r: "Undvik kombinationen. \u00d6verv\u00e4g alternativt antibiotikum eller muskelavslappnande medel." },
  { a: ["J01FA09"], b: ["N02CA"], s: "danger", t: "Ergotism \u2014 kontraindicerat", d: "Klaritromycin h\u00e4mmar CYP3A4 och \u00f6kar ergotaminkoncentrationen med risk f\u00f6r ergotism (vasospasm, ischemi).", r: "Kontraindicerat. \u00d6verv\u00e4g alternativt antibiotikum eller migr\u00e4nmedel." },
  { a: ["R03DA"], b: ["J01MA02"], s: "danger", t: "\u00d6kad teofyllinkoncentration \u2014 intoxikationsrisk", d: "Ciprofloxacin minskar metabolismen av teofyllin och kan orsaka intoxikation (takykardi, kramper).", r: "Undvik kombinationen om m\u00f6jligt. Vid n\u00f6dv\u00e4ndig samtidig behandling: halvera teofyllindosen och monitorera S-teofyllin." },
  { a: ["A10BA02"], b: ["C09A"], s: "warn", t: "\u00d6kad risk f\u00f6r laktatacidos", d: "ACE-h\u00e4mmare kan \u00f6ka risken f\u00f6r laktatacidos vid samtidig metforminbehandling, s\u00e4rskilt vid nedsatt njurfunktion.", r: "Monitorera njurfunktion. Var uppm\u00e4rksam p\u00e5 symtom p\u00e5 laktatacidos (illam\u00e5ende, buksm\u00e4rta, hyperventilation)." },
  { a: ["C09A"], b: ["A10A"], s: "warn", t: "\u00d6kad risk f\u00f6r hypoglykemi", d: "ACE-h\u00e4mmare kan \u00f6ka insulink\u00e4nsligheten och \u00f6ka risken f\u00f6r hypoglykemi hos diabetespatienter.", r: "Monitorera blodsocker noggrant vid ins\u00e4ttning och dos\u00e4ndring av ACE-h\u00e4mmare." },
  { a: ["M04AB"], b: ["J01C"], s: "warn", t: "\u00d6kad penicillinkoncentration", d: "Probenecid minskar njuruts\u00f6ndringen av penicilliner vilket f\u00f6rl\u00e4nger halveringstiden.", r: "Denna interaktion kan vara avsiktlig (anv\u00e4nds ibland terapeutiskt). Justera penicillindos vid behov." },
  { a: ["C03C"], b: ["N02BA01"], s: "warn", t: "Minskad diuretisk effekt och njurp\u00e5verkan", d: "NSAID kan minska den diuretiska effekten av loopdiuretika och \u00f6ka risken f\u00f6r akut njursvikt.", r: "Monitorera njurfunktion och v\u00e4tskestatus. \u00d6verv\u00e4g paracetamol." },
  { a: ["B01AC04"], b: ["B01AF01"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "Klopidogrel + rivaroxaban ger synergistisk antitrombotisk effekt med \u00f6kad bl\u00f6dningsrisk.", r: "Endast aktuellt vid specifika indikationer (t.ex. efter PCI). Noggrann nytta-risk-bed\u00f6mning." },
  { a: ["J01M"], b: ["M01A"], s: "warn", t: "S\u00e4nkt kramptr\u00f6skel \u2014 risk f\u00f6r kramper", d: "Fluorokinoloner i kombination med NSAID kan s\u00e4nka kramptr\u00f6skeln och utl\u00f6sa epileptiska anfall, s\u00e4rskilt hos \u00e4ldre och patienter med anamnes p\u00e5 kramper.", r: "\u00d6verv\u00e4g alternativt antibiotikum (t.ex. trimetoprim, nitrofurantoin). Informera patienten om symtom. Undvik kombinationen vid k\u00e4nd epilepsi." },

  // ===== PSYKOFARMAKA =====
  { a: ["N05AH02"], b: ["N06AB08"], s: "danger", t: "Kraftigt \u00f6kad klozapinkoncentration \u2014 intoxikationsrisk", d: "Fluvoxamin \u00e4r en stark CYP1A2-h\u00e4mmare och \u00f6kar klozapinkoncentrationen 5\u201310 g\u00e5nger med risk f\u00f6r allvarlig intoxikation.", r: "Kontraindicerat eller reducera klozapindosen till cirka 10 % av ursprungsdosen. Monitorera S-klozapin och \u00f6vervaka CNS-biverkningar." },
  { a: ["N03AF01"], b: ["G03A"], s: "warn", t: "Minskad effekt av hormonella preventivmedel", d: "Karbamazepin inducerar CYP3A4 och \u00f6kar metabolismen av \u00f6strogen och gestagener, vilket minskar effekten av p-piller, pl\u00e5ster och vaginala ringar.", r: "Rekommendera kompletterande barri\u00e4rskydd eller icke-hormonell preventivmetod. \u00d6verv\u00e4g kopparspiral." },
  { a: ["N03AF01"], b: ["N05AH04", "N05AX12"], s: "warn", t: "Minskad antipsykotisk effekt", d: "Karbamazepin inducerar CYP3A4 och minskar quetiapin- och aripiprazolniv\u00e5erna med 70\u201390 %, vilket kan leda till recidiv.", r: "F\u00f6rv\u00e4nta dig markant h\u00f6gre dosbehov. \u00d6verv\u00e4g antipsykotikum som inte metaboliseras via CYP3A4 (t.ex. olanzapin, paliperidon)." },
  { a: ["N03AF01"], b: ["N03AX09"], s: "warn", t: "Minskad lamotriginniv\u00e5", d: "Karbamazepin inducerar glukuronideringen av lamotrigin och minskar lamotriginniv\u00e5erna med 40\u201350 %, vilket kan ge recidiv vid epilepsi/bipol\u00e4r sjukdom.", r: "F\u00f6rv\u00e4nta dig h\u00f6gre lamotrigindoser. Monitorera klinisk effekt." },
  { a: ["N02AJ06", "R05DA04"], b: ["N06AB05", "N06AB03", "N06AX12"], s: "warn", t: "Minskad sm\u00e4rtlindrande effekt av kodein", d: "Kodein \u00e4r en prodrug som omvandlas till morfin via CYP2D6. Paroxetin, fluoxetin och bupropion h\u00e4mmar CYP2D6, vilket blockerar denna aktivering.", r: "F\u00f6rv\u00e4nta dig utebliven eller kraftigt reducerad effekt av kodein. \u00d6verv\u00e4g morfin eller annan opioid som inte kr\u00e4ver CYP2D6-aktivering." },

  // ===== CARDIOVASKUL\u00c4RT / NEFROLOGI =====
  { a: ["H02AB"], b: ["M01A"], s: "warn", t: "\u00d6kad risk f\u00f6r GI-bl\u00f6dning och ulcus", d: "Systemiska kortikosteroider + NSAID \u00f6kar risken additivt f\u00f6r \u00f6vre gastrointestinal bl\u00f6dning och ulcus, s\u00e4rskilt hos \u00e4ldre.", r: "\u00d6verv\u00e4g paracetamol som sm\u00e4rtlindring. Vid n\u00f6dv\u00e4ndig NSAID-behandling: kortast m\u00f6jliga tid, l\u00e4gsta dos, \u00f6verv\u00e4g gastroskydd (PPI)." },
  { a: ["B01AA03"], b: ["C01BD01"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk \u2014 INR-stegring", d: "Amiodaron h\u00e4mmar CYP2C9 och \u00f6kar warfarineffekten kraftigt med risk f\u00f6r allvarlig bl\u00f6dning.", r: "Minska warfarindosen med 30\u201350 % vid ins\u00e4ttning av amiodaron. Monitorera PK/INR inom 3\u20135 dagar och justera d\u00e4refter." },
  { a: ["B01AC04"], b: ["A02BC03"], s: "warn", t: "Minskad klopidogreleffekt", d: "Esomeprazol h\u00e4mmar CYP2C19 och minskar aktiveringen av klopidogrel, samma mekanism som omeprazol.", r: "\u00d6verv\u00e4g pantoprazol som alternativ PPI (svagare CYP2C19-h\u00e4mning)." },
  { a: ["L04AD01"], b: ["M01A"], s: "danger", t: "\u00d6kad risk f\u00f6r njurtoxicitet", d: "Ciklosporin och NSAID har additiv nefrotoxisk effekt som kan leda till akut njursvikt.", r: "Undvik kombinationen. \u00d6verv\u00e4g paracetamol som sm\u00e4rtlindring. Vid n\u00f6dv\u00e4ndig NSAID-behandling: monitorera njurfunktion och ciklosporinniv\u00e5er noggrant." },

  // ===== FAS 1: TCA-INTERAKTIONER =====
  { a: ["N06AA"], b: ["N06AF"], s: "danger", t: "Serotonergt syndrom \u2014 kontraindicerat", d: "TCA + MAO-h\u00e4mmare kan orsaka livshotande serotonergt syndrom med hypertermi, takykardi och neuromuskul\u00e4r hyperaktivitet.", r: "Minst 14 dagars uttv\u00e4ttningstid mellan TCA och MAO-h\u00e4mmare. \u00d6verv\u00e4g alternativ behandling." },
  { a: ["N06AA"], b: ["N06AB", "N06AX"], s: "danger", t: "\u00d6kad TCA-koncentration \u2014 intoxikationsrisk", d: "SSRI/SNRI h\u00e4mmar CYP2D6 och \u00f6kar TCA-koncentrationen med risk f\u00f6r antikolinerga och kardiella biverkningar.", r: "Monitorera S-TCA och \u00f6verv\u00e4g dosreduktion. V\u00e4lj SSRI/SNRI med svag CYP2D6-h\u00e4mning (citalopram, escitalopram, venlafaxin) om kombination kr\u00e4vs." },
  { a: ["N06AA"], b: ["C01BD01", "J01FA", "J01M", "J02AC", "N05A"], s: "danger", t: "F\u00f6rl\u00e4ngd QT-tid \u2014 risk f\u00f6r ventrikul\u00e4r arytmi", d: "TCA f\u00f6rl\u00e4nger QT-tiden additivt med andra QT-prolongerande l\u00e4kemedel med risk f\u00f6r torsades de pointes.", r: "Monitorera EKG vid samtidig behandling. \u00d6verv\u00e4g alternativ med mindre QT-p\u00e5verkan." },

  // ===== FAS 1: KARBAMAZEPIN/FENYTOIN - CYP-INDUKTION =====
  { a: ["N03AF01"], b: ["B01AA03"], s: "danger", t: "Minskad warfarineffekt \u2014 \u00f6kad risk f\u00f6r propp", d: "Karbamazepin inducerar CYP2C9 och \u00f6kar warfarins metabolism, vilket minskar INR och \u00f6kar risken f\u00f6r tromboembolism.", r: "Monitorera PK/INR vid ins\u00e4ttning och uts\u00e4ttning av karbamazepin. F\u00f6rv\u00e4nta dig \u00f6kat warfarinbehov. \u00d6verv\u00e4g DOAC som alternativ." },
  { a: ["N03AF01"], b: ["C10AA"], s: "warn", t: "Minskad statineffekt", d: "Karbamazepin inducerar CYP3A4 och minskar niv\u00e5erna av simvastatin och atorvastatin med risk f\u00f6r f\u00f6rs\u00e4mrad lipidkontroll.", r: "Monitorera lipidstatus. \u00d6verv\u00e4g rosuvastatin eller pravastatin som p\u00e5verkas mindre av CYP3A4-induktion." },
  { a: ["N03AF01"], b: ["B01AF01", "B01AF02", "B01AF03", "B01AE07"], s: "danger", t: "Minskad DOAC-effekt", d: "Karbamazepin inducerar CYP3A4 och/eller P-gp och minskar niv\u00e5erna av rivaroxaban, apixaban, edoxaban och dabigatran.", r: "Undvik kombinationen om m\u00f6jligt. \u00d6verv\u00e4g warfarin som alternativ (med t\u00e4tare INR-kontroll)." },
  { a: ["N03AF01"], b: ["N06AB", "N06AX"], s: "warn", t: "Minskad antidepressiv effekt", d: "Karbamazepin inducerar metabolismen av SSRI/SNRI via CYP3A4, vilket kan s\u00e4nka niv\u00e5erna och ge recidiv.", r: "Monitorera klinisk effekt. F\u00f6rv\u00e4nta dig h\u00f6gre dosbehov vid kombination med karbamazepin." },
  { a: ["N03AB05"], b: ["G03A", "B01AA03", "C10AA"], s: "danger", t: "Minskad effekt av flera l\u00e4kemedel", d: "Fenytoin \u00e4r en stark CYP-inducerare som \u00f6kar metabolismen av p-piller, warfarin och statiner med risk f\u00f6r utebliven effekt.", r: "Monitorera klinisk effekt och justera doser vid ins\u00e4ttning/uts\u00e4ttning av fenytoin. Rekommendera icke-hormonell preventivmetod." },

  // ===== FAS 1: AMIODARON =====
  { a: ["C01BD01"], b: ["C07A"], s: "danger", t: "Risk f\u00f6r bradykardi och AV-block", d: "Amiodaron har additiv negativ kronotrop och dromotrop effekt med betablockerare, med risk f\u00f6r uttalad bradykardi och AV-block.", r: "Monitorera EKG och hj\u00e4rtfrekvens. \u00d6verv\u00e4g dosreduktion av betablockerare vid ins\u00e4ttning av amiodaron." },
  { a: ["C01BD01"], b: ["C10AA"], s: "danger", t: "\u00d6kad statinkoncentration \u2014 rabdomyolysrisk", d: "Amiodaron h\u00e4mmar CYP3A4 och \u00f6kar niv\u00e5erna av simvastatin och atorvastatin med risk f\u00f6r myopati och rabdomyolys.", r: "Begr\u00e4nsa simvastatin till 20 mg/dag vid samtidig amiodaron. \u00d6verv\u00e4g rosuvastatin eller pravastatin som alternativ." },
  { a: ["C01BD01"], b: ["B01AF01", "B01AF02", "B01AF03", "B01AE07"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "Amiodaron h\u00e4mmar P-gp och/eller CYP3A4 och \u00f6kar niv\u00e5erna av DOAC med risk f\u00f6r bl\u00f6dning.", r: "Monitorera bl\u00f6dningsrisk. \u00d6verv\u00e4g dosreduktion av dabigatran enligt produktresum\u00e9. F\u00f6rsiktighet med rivaroxaban/apixaban." },
  { a: ["C01BD01"], b: ["C01BC04"], s: "danger", t: "\u00d6kad flekainidkoncentration", d: "Amiodaron h\u00e4mmar CYP2D6 och \u00f6kar flekainidniv\u00e5erna med risk f\u00f6r kardiell toxicitet.", r: "Minska flekainiddosen med 50 % vid samtidig amiodaron. Monitorera EKG." },

  // ===== FAS 1: MAKROLIDER =====
  { a: ["J01FA"], b: ["B01AA03"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk \u2014 INR-stegring", d: "Makrolider (erytromycin, klaritromycin, azitromycin) h\u00e4mmar warfarins metabolism med risk f\u00f6r INR-stegring och bl\u00f6dning.", r: "Monitorera PK/INR inom 3\u20135 dagar efter ins\u00e4ttning av makrolid. F\u00f6rv\u00e4nta dig dosreduktion av warfarin." },
  { a: ["J01FA"], b: ["B01AF01", "B01AF02", "B01AE07"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk", d: "Makrolider h\u00e4mmar CYP3A4 och/eller P-gp och \u00f6kar niv\u00e5erna av rivaroxaban, apixaban och dabigatran.", r: "Undvik kombinationen om m\u00f6jligt. \u00d6verv\u00e4g alternativt antibiotikum eller monitorera bl\u00f6dningsrisk." },
  { a: ["J01FA"], b: ["C10AA05"], s: "warn", t: "\u00d6kad statinkoncentration \u2014 risk f\u00f6r myopati", d: "Makrolider h\u00e4mmar CYP3A4 och \u00f6kar atorvastatinniv\u00e5erna med risk f\u00f6r myopati.", r: "\u00d6verv\u00e4g tillf\u00e4lligt uppeh\u00e5ll eller dosreduktion av atorvastatin under antibiotikakuren." },

  // ===== FAS 1: CIPROFLOXACIN + CYP1A2 =====
  { a: ["J01MA02"], b: ["N05AH02"], s: "danger", t: "Kraftigt \u00f6kad klozapinkoncentration \u2014 intoxikationsrisk", d: "Ciprofloxacin h\u00e4mmar CYP1A2 och \u00f6kar klozapinkoncentrationen markant med risk f\u00f6r allvarlig intoxikation.", r: "Undvik kombinationen. \u00d6verv\u00e4g alternativt antibiotikum. Om kombination kr\u00e4vs: reducera klozapindosen kraftigt och monitorera S-klozapin." },
  { a: ["J01MA02"], b: ["N05AH03"], s: "danger", t: "\u00d6kad olanzapinkoncentration", d: "Ciprofloxacin h\u00e4mmar CYP1A2 och \u00f6kar olanzapinniv\u00e5erna med risk f\u00f6r CNS-biverkningar.", r: "Monitorera CNS-biverkningar. \u00d6verv\u00e4g olanzapindosreduktion eller alternativt antibiotikum." },

  // ===== FAS 1: VALPROAT + KARBAPENEM =====
  { a: ["N03AG01"], b: ["J01DH"], s: "danger", t: "Kraftigt minskad valproatniv\u00e5 \u2014 recidivrisk", d: "Karbapenemer (meropenem, ertapenem) minskar valproatniv\u00e5erna med 60\u201390 % inom 24 timmar, med risk f\u00f6r epileptiska anfall.", r: "Undvik kombinationen. \u00d6verv\u00e4g alternativt antibiotikum. Om oundvikligt: monitorera S-valproat och f\u00f6rv\u00e4nta dig markant dos\u00f6kning." },

  // ===== FAS 1: TOPIRAMAT + P-PILLER =====
  { a: ["N03AX11"], b: ["G03A"], s: "warn", t: "Minskad effekt av p-piller", d: "Topiramat minskar effekten av hormonella preventivmedel vid doser \u00f6ver 200 mg/dag, med risk f\u00f6r oplanerad graviditet.", r: "Rekommendera kompletterande barri\u00e4rskydd vid topiramatdoser \u00f6ver 200 mg/dag. \u00d6verv\u00e4g icke-hormonell metod." },

  // ===== FAS 1: METFORMIN + JODKONTRAST =====
  { a: ["A10BA02"], b: ["V08A"], s: "danger", t: "\u00d6kad risk f\u00f6r laktatacidos", d: "Jodkontrast kan orsaka akut njurp\u00e5verkan och \u00f6ka risken f\u00f6r metforminassocierad laktatacidos.", r: "S\u00e4tt ut metformin 48 timmar f\u00f6re planerad kontrastmedelsunders\u00f6kning. \u00c5terins\u00e4tt tidigast 48 timmar efter\u00e5t om njurfunktionen \u00e4r of\u00f6r\u00e4ndrad." },

  // ===== FAS 1: LITIUM + SSRI =====
  { a: ["N05AN01"], b: ["N06AB"], s: "warn", t: "\u00d6kad risk f\u00f6r serotonergt syndrom och litiumtoxicitet", d: "SSRI kan \u00f6ka litiumkoncentrationen och ge additiv serotonerg effekt med risk f\u00f6r intoxikation.", r: "Monitorera S-litium inom 1 vecka efter ins\u00e4ttning av SSRI. Var uppm\u00e4rksam p\u00e5 symtom p\u00e5 serotonergt syndrom." },

  // ===== FAS 2: SULFONUREIDER =====
  { a: ["A10BB"], b: ["J02AC01"], s: "danger", t: "\u00d6kad risk f\u00f6r hypoglykemi", d: "Flukonazol h\u00e4mmar CYP2C9 och minskar metabolismen av sulfonureider med risk f\u00f6r allvarlig hypoglykemi.", r: "Monitorera blodsocker noggrant. F\u00f6rv\u00e4nta dig dosreduktion av sulfonureid. \u00d6verv\u00e4g alternativt antimykotikum." },
  { a: ["A10BB"], b: ["B01AA03"], s: "warn", t: "\u00d6kad risk f\u00f6r hypoglykemi och INR-stegring", d: "Sulfonureider kan potentiera warfarineffekten via proteindisplacement, med risk f\u00f6r b\u00e5de hypoglykemi och bl\u00f6dning.", r: "Monitorera blodsocker och PK/INR vid ins\u00e4ttning/uts\u00e4ttning av sulfonureid." },
  { a: ["J02AC01"], b: ["N03AB05"], s: "danger", t: "\u00d6kad fenytoinkoncentration", d: "Flukonazol h\u00e4mmar CYP2C9 och \u00f6kar fenytoinniv\u00e5erna med risk f\u00f6r intoxikation.", r: "Monitorera S-fenytoin vid ins\u00e4ttning av flukonazol. F\u00f6rv\u00e4nta dig dosreduktion av fenytoin." },
  { a: ["J01FA09"], b: ["N03AF01"], s: "danger", t: "\u00d6kad karbamazepinkoncentration", d: "Klaritromycin h\u00e4mmar CYP3A4 och \u00f6kar karbamazepinniv\u00e5erna med risk f\u00f6r intoxikation.", r: "Monitorera S-karbamazepin och biverkningar. F\u00f6rv\u00e4nta dig dosreduktion av karbamazepin." },
  { a: ["C07AB02"], b: ["N06AB05", "N06AB03"], s: "warn", t: "\u00d6kad metoprololeffekt \u2014 bradykardi", d: "Paroxetin och fluoxetin h\u00e4mmar CYP2D6 och \u00f6kar metoprololniv\u00e5erna avsev\u00e4rt med risk f\u00f6r bradykardi och hypotension.", r: "Monitorera hj\u00e4rtfrekvens och blodtryck. \u00d6verv\u00e4g metoprololdosreduktion eller byte till atenolol/bisoprolol." },
  { a: ["H02AB"], b: ["J01M"], s: "warn", t: "\u00d6kad risk f\u00f6r senskada", d: "Systemiska kortikosteroider \u00f6kar risken f\u00f6r fluorokinolonassocierad tendinit och senruptur.", r: "Undvik kombinationen hos \u00e4ldre och vid tidigare senbesv\u00e4r. \u00d6verv\u00e4g alternativt antibiotikum." },
  { a: ["H02AB"], b: ["A10A", "A10BA", "A10BB"], s: "warn", t: "F\u00f6rh\u00f6jt blodsocker", d: "Systemiska kortikosteroider motverkar effekten av insulin och orala diabetesl\u00e4kemedel med risk f\u00f6r hyperglykemi.", r: "Monitorera blodsocker noggrant. F\u00f6rv\u00e4nta dig \u00f6kat behov av diabetesl\u00e4kemedel under steroidbehandling." },
  { a: ["C09DX04"], b: ["C09A", "C09C"], s: "danger", t: "Kontraindicerat \u2014 risk f\u00f6r angio\u00f6dem", d: "Sacubitril/valsartan i kombination med ACE-h\u00e4mmare \u00f6kar risken f\u00f6r angio\u00f6dem avsev\u00e4rt. Minst 36 timmars uppeh\u00e5ll vid byte.", r: "Kontraindicerat. S\u00e4tt ut ACE-h\u00e4mmare minst 36 timmar f\u00f6re ins\u00e4ttning av sacubitril/valsartan." },
  { a: ["J01EE01"], b: ["B01AA03"], s: "danger", t: "\u00d6kad bl\u00f6dningsrisk \u2014 INR-stegring", d: "Kotrimoxazol inneh\u00e5ller trimetoprim som h\u00e4mmar warfarins metabolism och kan orsaka INR-stegring och bl\u00f6dning.", r: "Monitorera PK/INR inom 3\u20135 dagar vid ins\u00e4ttning. F\u00f6rv\u00e4nta dig dosreduktion av warfarin." },
  { a: ["G03A"], b: ["N03AX09"], s: "warn", t: "Minskad lamotriginniv\u00e5", d: "Hormonella preventivmedel \u00f6kar glukuronideringen av lamotrigin och minskar lamotriginniv\u00e5erna med cirka 50 %.", r: "Monitorera klinisk effekt vid ins\u00e4ttning/uts\u00e4ttning av p-piller. F\u00f6rv\u00e4nta dig \u00e4ndrat lamotriginbehov." },
  { a: ["N05A"], b: ["C01BD01", "J01FA", "J01M", "J02AC"], s: "warn", t: "\u00d6kad risk f\u00f6r QT-f\u00f6rl\u00e4ngning", d: "Antipsykotika kan f\u00f6rl\u00e4nga QT-tiden additivt med andra QT-prolongerande l\u00e4kemedel.", r: "Monitorera EKG vid kombination av antipsykotika med andra QT-prolongerande l\u00e4kemedel." },
  { a: ["B01AC04"], b: ["N06AB", "N06AX"], s: "warn", t: "\u00d6kad bl\u00f6dningsrisk", d: "SSRI/SNRI \u00f6kar bl\u00f6dningsrisken vid klopidogrelbehandling genom additiv p\u00e5verkan p\u00e5 trombocytaggregationen.", r: "Monitorera bl\u00f6dningssymtom. \u00d6verv\u00e4g mirtazapin som alternativt antidepressivum." },

  // ===== FAS 3: MEDEL PRIORITET =====
  { a: ["A02BC"], b: ["B03AA"], s: "warn", t: "Minskad j\u00e4rnabsorption", d: "PPI h\u00f6jer magsackets pH och minskar absorptionen av j\u00e4rnpreparat, vilket kan f\u00f6rs\u00e4mra behandlingseffekten.", r: "Ta j\u00e4rnpreparat med minst 2\u20134 timmars mellanrum fr\u00e5n PPI. \u00d6verv\u00e4g askorbinsyra f\u00f6r att \u00f6ka absorptionen." },
  { a: ["A10BA02"], b: ["N03AX11"], s: "warn", t: "\u00d6kad risk f\u00f6r acidos", d: "Metformin och topiramat har b\u00e5da risk f\u00f6r metabol acidos. Additiv effekt kan leda till symtomatisk acidos.", r: "Monitorera bikarbonat/v\u00e4tejoner i serum vid samtidig behandling. Var uppm\u00e4rksam p\u00e5 acidossymtom." },
  { a: ["J01FA10"], b: ["C01BD01", "J01M", "J02AC", "N05A"], s: "warn", t: "M\u00f6jlig f\u00f6rl\u00e4ngning av QT-tid", d: "Azitromycin kan f\u00f6rl\u00e4nga QT-tiden additivt med andra QT-prolongerande l\u00e4kemedel.", r: "Monitorera EKG vid kombination med andra QT-p\u00e5verkande l\u00e4kemedel." },
  { a: ["N05AN01"], b: ["N05A"], s: "warn", t: "\u00d6kad risk f\u00f6r neurotoxicitet", d: "Litium och antipsykotika kan i kombination ge additiv eller synergistisk neurotoxicitet med f\u00f6rvirring, tremor och kramper.", r: "Monitorera neurologiska symtom. \u00d6verv\u00e4g S-litium och dosjustering." },
  { a: ["N05AN01"], b: ["C09C"], s: "warn", t: "\u00d6kad litiumkoncentration", d: "ARB kan minska njurclearance av litium och \u00f6ka risken f\u00f6r litiumintoxikation, samma mekanism som ACE-h\u00e4mmare.", r: "Monitorera S-litium noggrant. \u00d6verv\u00e4g alternativt antihypertensivum." },
  { a: ["C01AA05"], b: ["J01FA"], s: "danger", t: "\u00d6kad digoxinkoncentration", d: "Makrolider h\u00e4mmar P-gp och \u00f6kar digoxinabsorptionen med risk f\u00f6r digoxintoxikation.", r: "Monitorera S-digoxin och EKG. F\u00f6rv\u00e4nta dig dosreduktion av digoxin vid makrolidbehandling." },
  { a: ["C01AA05"], b: ["C03A", "C03C"], s: "warn", t: "\u00d6kad risk f\u00f6r digoxintoxikation", d: "Diuretika kan orsaka hypokalemi och hypomagnesemi, vilket \u00f6kar digoxinets kardiella toxicitet \u00e4ven vid normala S-digoxinniv\u00e5er.", r: "Monitorera S-kalium och S-magnesium. Korrigera elektrolytrubbningar f\u00f6re digoxindosjustering." },
  { a: ["N03AA02"], b: ["G03A"], s: "warn", t: "Minskad effekt av p-piller", d: "Fenobarbital inducerar CYP3A4 och \u00f6kar metabolismen av hormonella preventivmedel.", r: "Rekommendera icke-hormonell preventivmetod eller kompletterande barri\u00e4rskydd." },
  { a: ["N03AA02"], b: ["B01AA03"], s: "danger", t: "Minskad warfarineffekt", d: "Fenobarbital inducerar CYP2C9 och CYP3A4 och minskar warfarinniv\u00e5erna med risk f\u00f6r propp.", r: "Monitorera PK/INR vid ins\u00e4ttning/uts\u00e4ttning. F\u00f6rv\u00e4nta dig \u00f6kat warfarinbehov." },
  { a: ["M01AE01", "M01AB05", "M01AC06"], b: ["B01AC06"], s: "warn", t: "Minskad trombocyth\u00e4mmande effekt", d: "Ibuprofen, diklofenak och meloxikam kan interferera med l\u00e5gdos-ASAs antiaggregatoriska effekt genom kompetition vid COX-1.", r: "Ta ibuprofen minst 30 minuter efter ASA (eller 8 timmar f\u00f6re). \u00d6verv\u00e4g paracetamol eller naproxen som alternativ." },
  { a: ["A10BA02"], b: ["C09C"], s: "warn", t: "\u00d6kad risk f\u00f6r laktatacidos", d: "ARB kan p\u00e5verka njurfunktionen och d\u00e4rmed \u00f6ka risken f\u00f6r metforminassocierad laktatacidos, s\u00e4rskilt vid nedsatt njurfunktion.", r: "Monitorera njurfunktion. Var uppm\u00e4rksam p\u00e5 symtom p\u00e5 laktatacidos." },
  { a: ["H02AB"], b: ["C03A", "C03C"], s: "warn", t: "\u00d6kad risk f\u00f6r hypokalemi", d: "Kortikosteroider och diuretika har additiv kaliumf\u00f6rlust via olika mekanismer, vilket \u00f6kar risken f\u00f6r hypokalemi.", r: "Monitorera S-kalium regelbundet. \u00d6verv\u00e4g kaliumtillskott vid behov." },
  { a: ["J02AC03"], b: ["N03AF01"], s: "danger", t: "Kontraindicerat \u2014 kraftigt reducerad vorikonazoleffekt", d: "Karbamazepin inducerar CYP3A4 och minskar vorikonazolniv\u00e5erna kraftigt, med risk f\u00f6r utebliven antimykotisk effekt.", r: "Kontraindicerat. \u00d6verv\u00e4g alternativt antimykotikum eller antiepileptikum." },
  { a: ["B01AC04"], b: ["A02BC", "A02BC03"], s: "warn", t: "Minskad klopidogreleffekt", d: "Lansoprazol och andra PPI h\u00e4mmar CYP2C19 och minskar aktiveringen av klopidogrel, samma mekanism som omeprazol.", r: "\u00d6verv\u00e4g pantoprazol som har svagare CYP2C19-h\u00e4mning." },
  { a: ["J02AC"], b: ["A02BC"], s: "warn", t: "Minskad effekt av azol-antimykotika", d: "PPI h\u00f6jer magsackets pH och kan minska absorptionen av vissa azol-antimykotika (s\u00e4rskilt itrakonazol och posakonazol).", r: "Ta azol-antimykotika med sur dryck (t.ex. l\u00e4sk) och med minst 2 timmars mellanrum fr\u00e5n PPI." },

];

function atcMatches(atcCode, pattern) {
  return atcCode ? atcCode.startsWith(pattern) : false;
}

function CHECK_INTERACTIONS(atcEntries) {
  var warnings = [];
  for (var i = 0; i < INTERACTIONS.length; i++) {
    var ix = INTERACTIONS[i];
    for (var x = 0; x < atcEntries.length; x++) {
      for (var y = x + 1; y < atcEntries.length; y++) {
        var matchAB = ix.a.some(function(p) { return atcMatches(atcEntries[x].a, p); })
                   && ix.b.some(function(p) { return atcMatches(atcEntries[y].a, p); });
        var matchBA = ix.a.some(function(p) { return atcMatches(atcEntries[y].a, p); })
                   && ix.b.some(function(p) { return atcMatches(atcEntries[x].a, p); });
        if (matchAB || matchBA) {
          var already = false;
          for (var w = 0; w < warnings.length; w++) {
            if (warnings[w].t === ix.t && warnings[w].drugs[0] === atcEntries[x].i && warnings[w].drugs[1] === atcEntries[y].i) {
              already = true;
              break;
            }
          }
          if (!already) {
            warnings.push({
              s: ix.s,
              t: ix.t,
              d: ix.d,
              r: ix.r,
              drugs: [atcEntries[x].i, atcEntries[y].i]
            });
          }
        }
      }
    }
  }
  return warnings;
}
